### ISSUE TITLE
Controller returns Trainer Handle and Pokemon Names in all lower case

### ISSUE THREAD

**Issue by srosy** [Abyssalisk/2450-PokeApiProject#28]
The first letter should be capitalized on every view for anything that is a name across the Web project--this includes Trainer handles, Pokemon names, and move names. Either a fix needs to be added to PokemonController.cs and LoginController.cs, or in the services consuming the controllers.

![image](https://user-images.githubusercontent.com/30061719/87338021-ac9f9480-c501-11ea-8692-38579413bbcd.png)

**Comment by srosy** [comment]
@TheUbMunster Want to tackle this one?

**Comment by TheUbMunster** [comment]
Can you check and see if my change works? It's not letting me access my account on my machine (probably because my account info was on the console app only) but I don't have time rn.

**Comment by srosy** [comment]
@TheUbMunster This looks good so far. The only thing that doesn't look right is that the move names should also be capitalized on the first letter, and the first letter after a dash. 

![image](https://user-images.githubusercontent.com/30061719/87578863-4d24be80-c692-11ea-8a28-e0de4aaa120f.png)

**Comment by srosy** [comment]
@TheUbMunster Works, thanks for getting this done.
