### ISSUE TITLE
New Lineup Looks Like SHIT

### ISSUE THREAD

**Issue by srosy** [Abyssalisk/2450-PokeApiProject#29]
When creating a new team and selection pokemon, before the moves selection, right now we have a placeholder for team selections with a list of checkboxes and the respective pokemon's name. We need a better UI. 

![image](https://user-images.githubusercontent.com/30061719/87338310-32234480-c502-11ea-912f-4cba9d7b64a7.png)

**Comment by Morgan-Mischo** [comment]
I can start working on this issue

**Comment by DrechslerDerek** [comment]
Fixed =, styling is on par with rest of site
