### ISSUE TITLE
Redesign the TrainerInfoComponent and PokemonInfoComponent so they look pretty

### ISSUE THREAD

**Issue by nmuelle1slcc** [Abyssalisk/2450-PokeApiProject#38]
The TrainerInfoComponent and PokemonInfoComponent are pretty barebones rn. Redesign them so they look more video-game-like or more Pokemon-y. All the data we need is there, we just need prettier CSS at this point.

![championpage](https://user-images.githubusercontent.com/66232591/87863023-deef2e80-c913-11ea-9c29-1f9faf8bac59.png)

**Comment by srosy** [comment]
@nmuelle1slcc Is this Morgan's assignment?

**Comment by nmuelle1slcc** [comment]
> @nmuelle1slcc Is this Morgan's assignment?

Yes

**Comment by srosy** [comment]
commit #62 closes
