### ISSUE TITLE
Initialization exception "Failed to find a valid digest in the 'integrity' attribute for resource '...'" The resource has been blocked.

### ISSUE THREAD

**Issue by TheUbMunster** [Abyssalisk/2450-PokeApiProject#43]
Don't know what's causing this.
![Screenshot (48)](https://user-images.githubusercontent.com/66451362/87866170-98adc580-c93b-11ea-8c3d-7bfa4ab10e68.png)
![Screenshot (49)](https://user-images.githubusercontent.com/66451362/87866238-6fda0000-c93c-11ea-8b93-e9f40ff29fa8.png)

**Comment by srosy** [comment]
@TheUbMunster please provide steps and any other contingencies to recreate the bug.

**Comment by srosy** [comment]
@TheUbMunster reverted code back, please create branch next time instead of pushing directly to master.
