### ISSUE TITLE
Moves Selection DDL Cosmetics

### ISSUE THREAD

**Issue by srosy** [Abyssalisk/2450-PokeApiProject#52]
1. Update tags on moves to match pokemon type tags for better type clarity
2. Add pascal case to move names.

![image](https://user-images.githubusercontent.com/30061719/88060976-264c0980-cb24-11ea-8798-471000ae52ef.png

**Comment by srosy** [comment]
@bsilvafe1 How's this coming?It should only take an hour or so

**Comment by bsilvafe1** [comment]
> @bsilvafe1 How's this coming?It should only take an hour or so

Hi Spencer. I did, capitalized on the types and movements. I couldn't finish the colored badge on Tuesday. I've been busy with work these two days. I'm planning to finish it. tomorrow after work. Are you ok with that or do you need this to be done today?

**Comment by srosy** [comment]
commit #61 closes
