### ISSUE TITLE
Scoreboard Update

### ISSUE THREAD

**Issue by srosy** [Abyssalisk/2450-PokeApiProject#56]
Scoreboard needs to show actual scoreboard values from the DB and order by score.

**Comment by TheUbMunster** [comment]
Look at sams_other_stuff and see if the sorting works for you.

For the scoreboard values there might need to be some DB normalization and some edits, so I'll get to talking with Mr DB man himself about that.

**Comment by srosy** [comment]
@TheUbMunster Can you make a pull request for your branch and tie it to this issue? Then I can review.
